Repository LEARNAcademy/prework_backend, pull requests merged in 2020-05, with the labels that each got.

#45 Add controller spec file for code, lessons, questions and resources.
  spec/controllers/code_module_controller_spec.rb
  spec/controllers/lessons_controller_spec.rb
  spec/controllers/questions_controller_spec.rb
  spec/controllers/resources_controller_spec.rb
  spec/helpers/resources_helper_spec.rb
  spec/rails_helper.rb
Labels: testing

#78 Disable auth token
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/models/user.rb
  config/routes.rb
Labels: bug

#81 Add admin column to users model.
  db/migrate/20200507223242_add_admin_boolean_to_users.rb
  db/schema.rb
Labels: enhancement

#86 Add JWT gem and configurations
  Gemfile
  Gemfile.lock
  app/models/jwt_blacklist.rb
  app/models/user.rb
  config/initializers/devise.rb
  db/migrate/20200511203337_create_jwt_blacklists.rb
  db/schema.rb
  spec/models/jwt_blacklist_spec.rb
Labels: enhancement

#94 Add user controller and route
  app/controllers/users_controller.rb
  config/routes.rb
Labels: enhancement

#95 Add json render with conditionals for user controller
  app/controllers/users_controller.rb
Labels: enhancement

#98 Updated README
  README.md
  app/controllers/users_controller.rb
Labels: documentation
